services:

  api:
    container_name: ptt-api
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9090:9090
    environment:
      TURSO_DATABASE_URL: ${TURSO_DATABASE_URL}
      TURSO_AUTH_TOKEN: ${TURSO_AUTH_TOKEN}

      SERVER_VERSION: ${SERVER_VERSION}
      SERVER_ENV: ${SERVER_ENV}
      SERVER_ADDR: ${SERVER_ADDR}
      SERVER_READ_TIMEOUT: ${SERVER_READ_TIMEOUT}
      SERVER_WRITE_TIMEOUT: ${SERVER_WRITE_TIMEOUT}
      SERVER_IDLE_TIMEOUT: ${SERVER_IDLE_TIMEOUT}
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./.air.toml:/app/.air.toml
      - /app/tmp

  web: 
    container_name: ptt-web
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    environment:
      API_BASE_URL: "http://api:9090"
    volumes:
      - ./web/src:/app/src
      - ./web/static:/app/static
