services:

  api:
    container_name: ptt-api
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 9091:9090
    environment:
      TURSO_DATABASE_URL: ${TURSO_DATABASE_URL}
      TURSO_AUTH_TOKEN: ${TURSO_AUTH_TOKEN}

      SERVER_VERSION: ${SERVER_VERSION}
      SERVER_ENV: production
      SERVER_ADDR: ${SERVER_ADDR}
      SERVER_READ_TIMEOUT: ${SERVER_READ_TIMEOUT}
      SERVER_WRITE_TIMEOUT: ${SERVER_WRITE_TIMEOUT}
      SERVER_IDLE_TIMEOUT: ${SERVER_IDLE_TIMEOUT}

      RESEND_API_KEY: ${RESEND_API_KEY}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      ORIGIN: ${ORIGIN}
      API_BASE_URL: http://api:9090
    ports:
      - 3032:3032
